name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Update module.json version
      run: |
        sed -i 's/"version": ".*"/"version": "${{ steps.extract_version.outputs.VERSION }}"/' module.json
        
    - name: Create module archive
      run: |
        zip -r pf2e-npc-vibes.zip . \
          -x "*.git*" \
          -x "*.github*" \
          -x "*.md" \
          -x "node_modules/*" \
          -x "*.log"
          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.extract_version.outputs.VERSION }}
        body: |
          ## Changes in this Release
          
          Please see [CHANGELOG.md](https://github.com/PadreMontoya/pf2e-npc-vibes/blob/main/CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          **Manifest URL:** `https://github.com/PadreMontoya/pf2e-npc-vibes/releases/latest/download/module.json`
          
          ## Compatibility
          
          - **Foundry VTT:** v12+
          - **PF2E System:** v5.0.0+
        draft: false
        prerelease: false
        
    - name: Upload module.json
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module.json
        asset_name: module.json
        asset_content_type: application/json
        
    - name: Upload module archive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pf2e-npc-vibes.zip
        asset_name: pf2e-npc-vibes.zip
        asset_content_type: application/zip
